//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalHubAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerOrderDetail
    {
        public int Id { get; set; }
        public int LineId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public int qty { get; set; }
    
        public virtual customerOrder customerOrder { get; set; }
    }
}
