//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalHubAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerOrder
    {
        public customerOrder()
        {
            this.customerOrderDetails = new HashSet<customerOrderDetail>();
        }
    
        public int Id { get; set; }
        public string OrderReference { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int OrderType { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual StatusList StatusList { get; set; }
        public virtual ICollection<customerOrderDetail> customerOrderDetails { get; set; }
    }
}
