//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalHubAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusList
    {
        public StatusList()
        {
            this.customerOrders = new HashSet<customerOrder>();
        }
    
        public int StateId { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual ICollection<customerOrder> customerOrders { get; set; }
    }
}
